### ISSUE TITLE
Consider bumping reqwest and libloading versions

### ISSUE THREAD

**Issue by StevenLu2004** [Michael-F-Bryan/plugins_in_rust#2]
Thank you so much for writing this tutorial. It helped me a lot.

The major difficulty I faced as I tried to follow the tutorial myself is the version changes in `reqwest` (which adopted async/await) and `libloading` (which ditched `std::io::Error` in favor of `libloading::Error`, causing `ExternalFunctions::load` to break). I think the tutorial will be more straightforward if the dependencies are the latest versions. Thank you again :)

**Comment by Michael-F-Bryan** [comment]
Can you point out which parts of the tutorial need updating?

**Comment by wlthomson** [comment]
Also want to say a big thanks for writing this tutorial!

I faced similar issues with outdated dependencies. For my own research, I bumped the dependencies and found it was pretty easy to migrate the existing code to the newer versions. I've made a PR for this issue, let me know if it's helpful!

**Comment by Michael-F-Bryan** [comment]
See https://github.com/Michael-F-Bryan/plugins_in_rust/pull/3#issuecomment-904318784.
