### ISSUE TITLE
Inconsistent `cargo run` examples

### ISSUE THREAD

**Issue by wlthomson** [Michael-F-Bryan/plugins_in_rust#4]
As others have already said, thanks for providing this tutorial. It's been very helpful.

Just a minor issue: the example `cargo run` commands load different `libplugins_random.so` builds (`target/release` vs. `target/debug`): 

```
$ cargo run -- ../target/release/libplugins_random.so random
...
```

```
cargo run -- ../target/debug/libplugins_random.so random
...
```

Although I assume it doesn't make any difference in practice, the inconsistency adds potential for confusion. To remove any ambiguity, it might be worth prefacing these examples with instructions for (re)building the executable and libraries.

**Comment by Michael-F-Bryan** [comment]
Thanks for pointing this out. Did you mean to create the issue against the tutorial repo ([Michael-F-Bryan/adventures.michaelfbryan.com](https://github.com/Michael-F-Bryan/adventures.michaelfbryan.com)) or would it be a code change for this repo?

**Comment by wlthomson** [comment]
Apologies, I didn't see there was a separate repo for the blog post!

Will move my issue over there, feel free to close this one out.
